#!/usr/bin/ruby

begin
    re = Regexp.compile(ARGV[0].to_s)
    f = open(ARGV[1].to_s)
rescue => exception
    puts "RECHK-Error\t" + $!.to_s
    exit
end

r = nil
c = 0

f.each do |l|
    c += 1 if r = re =~ l
end

p c
f.close
